version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: unipass-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - unipass-network

volumes:
  postgres_data:

networks:
  unipass-network:
    driver: bridge